# 0. Install Dependencies and Bring in Data

In [1]:
%pip install tensorflow pandas matplotlib scikit-learn

Requirement already satisfied: tensorflow in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (2.21.0)
Requirement already satisfied: pandas in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (3.0.6)
Requirement already satisfied: matplotlib in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (3.11.2)
Requirement already satisfied: scikit-learn in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (1.9.1)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (2.5.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (7.36.2)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (84.0.0)
Requirement already satisfied: six>=1.12.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (2.5.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (1.84.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (2.5.4)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from matplotlib) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: pillow>=9 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from matplotlib) (13.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: rich in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\maryam\comment-toxicity-classifier\.venv\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: C:\Users\Maryam\comment-toxicity-classifier\.venv\Scripts\python.exe -m pip install --upgrade pip

In [2]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np

In [3]:
df = pd.read_csv(os.path.join('jigsaw-toxic-comment-classification-challenge', 'train.csv', 'train.csv'))

In [4]:
df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

In [5]:
df.tail()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0

In [6]:
df.iloc[6]['comment_text']

'COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK'

In [7]:
df[df.columns[2:]].iloc[6]

toxic            1
severe_toxic     1
obscene          1
threat           0
insult           1
identity_hate    0
Name: 6, dtype: int64

# 1. Preprocess

In [8]:
%pip list

Package                 Version
----------------------- -----------
absl-py                 2.5.1
asttokens               3.0.2
astunparse              1.6.3
certifi                 2026.7.22
charset-normalizer      3.5.2
cloudpickle             3.1.2
colorama                0.4.6
comm                    0.2.3
contourpy               1.4.0
cycler                  0.12.1
debugpy                 1.8.22
executing               2.3.0
flatbuffers             25.12.19
fonttools               4.67.0
gast                    0.7.0
google-pasta            0.2.0
grpcio                  1.84.0
h5py                    3.14.0
idna                    3.20
ipykernel               7.4.0
ipython                 9.17.1
ipython_pygments_lexers 1.1.1
jedi                    0.20.1
joblib                  1.6.0
jupyter_client          8.10.0
jupyter_core            5.9.1
kagglehub               1.0.2
kagglesdk               0.1.37
keras                   3.15.1
kiwisolver              1.5.1
libclang                18.1.1
markdown-it-py          4.2.0
matplotlib              3.11.2
matplotlib-inline       0.2.2
mdurl                   0.1.2
ml_dtypes               0.6.0
namex                   0.1.0
narwhals                2.27.1
nest-asyncio2           1.7.4
numpy                   2.5.4
opt_einsum              3.4.0
optree                  0.20.0
packaging               26.3
pandas                  3.0.6
parso                   0.8.7
pillow                  13.0.0
pip                     25.2
platformdirs            4.13.4
prompt_toolkit          3.0.53
protobuf                7.36.2
psutil                  7.2.2
pure_eval               0.2.4
Pygments                2.21.0
pyparsing               3.3.3
python-dateutil         2.9.0.post0
PyYAML                  6.0.3
pyzmq                   27.2.0
requests                2.34.2
rich                    15.0.0
scikit-learn            1.9.1
scipy                   1.18.1
setuptools              84.0.0
six                     1.17.0
stack-data              0.6.3
tensorflow              2.21.0
termcolor               3.3.0
threadpoolctl           3.7.0
tornado                 6.5.10
tqdm                    4.70.1
traitlets               5.16.1
typing_extensions       4.16.0
tzdata                  2026.5
urllib3                 2.8.0
wcwidth                 0.9.2
wheel                   0.48.0
wrapt                   2.5.1
Note: you may need to restart the kernel to use updated packages.

In [9]:
from tensorflow.keras.layers import TextVectorization

In [10]:
X = df['comment_text']
y = df[df.columns[2:]].values

In [11]:
df[df.columns[2:]].values

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], shape=(159571, 6))

In [12]:
X

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: str

In [13]:
y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], shape=(159571, 6))

In [14]:
MAX_FEATURES = 200000 # numbers of words in vocab

In [15]:
vectorizer = TextVectorization(max_tokens= MAX_FEATURES, 
                              output_sequence_length = 1800,
                              output_mode = 'int')

In [16]:
type(X.values)

pandas.arrays.StringArray

In [17]:
vectorizer.adapt(X.values)

In [18]:
vectorizer('Hello world life is sad')[:5]

In [ ]:
vectorizer.get_vocabulary()

In [20]:
vectorized_text = vectorizer(X.values)

In [21]:
len(X)

159571

In [22]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]],
      shape=(159571, 1800))>

In [23]:
#MCSHBAP - map, cache, shuffel, batch, prefetch from tensor_slices, list_file

dataset = tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8) #helps preventing bottleneck

In [24]:
batch_X , batch_y = dataset.as_numpy_iterator().next()

In [25]:
batch_X.shape

(16, 1800)

In [26]:
batch_y.shape

(16, 6)

In [27]:
train = dataset.take(int(len(dataset)*.7))
val = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [28]:
train_generator = train.as_numpy_iterator()

In [29]:
train_generator.next()

(array([[     5,   1418,      1, ...,      0,      0,      0],
        [    37,      8,    499, ...,      0,      0,      0],
        [     8,    253,     22, ...,      0,      0,      0],
        ...,
        [ 40656,     43,    158, ...,      0,      0,      0],
        [   451, 129604,   5770, ...,      0,      0,      0],
        [  3560,  22176,      4, ...,      0,      0,      0]],
       shape=(16, 1800)),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]))

# 2. Create Sequential Model

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [31]:
y[0]

array([0, 0, 0, 0, 0, 0])

In [32]:
model = Sequential()
# Create the embedding layer
model.add(Embedding(MAX_FEATURES+1, 32))
# Bidrectional LSTM layer
model.add(Bidirectional(LSTM(32, activation='tanh')))
# Feature extractor Fully connected layers
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
# Final layers
model.add(Dense(6, activation='sigmoid'))

In [33]:
model.compile(loss='BinaryCrossentropy', optimizer='Adam')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [34]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional (Bidirectional)        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(train, epochs=1, validation_data=val)

C:\Users\Maryam\comment-toxicity-classifier\.venv\Lib\site-packages\keras\src\trainers\epoch_iterator.py:74: UserWarning: `shuffle=True` was passed, but will be ignored since the data `x` was provided as a tf.data.Dataset. The Dataset is expected to already be shuffled (via `.shuffle(buffer_size)`).
  self.data_adapter = data_adapters.get_data_adapter(

1178/6981 ━━━━━━━━━━━━━━━━━━━━ 1:12:03 745ms/step - loss: 0.0949

In [ ]:
history.history

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
plt.figure(figsize=(8,5))
pd.DataFrame(history.history).plot()
plt.show()